In [ ]:
# If we have 1000 datapoints and has 900 yes and 100 no
# it is 9:1 ratio so it is the imbalanced dataset
# if we handle imbalanced dataset then model will lean towards the highest side in machine learning
# Upsampling
# Downsampling

In [ ]:
#Up sampling
import numpy as np
import pandas as pd

#set the random sedd for reproducibility
np.random.seed(123)

#create the dataframe with two classes
n_samples = 1000 #Taking the class sample size is 1000
class_0_ratio = 0.9 #first class ratio is 90 %
n_class_0 = int(n_samples*class_0_ratio) #number of people in class0
n_class_1 = n_samples - n_class_0 #number of people in class 1

In [4]:
n_class_0,n_class_1

(900, 100)

In [ ]:
#Create my dataframe with imbalance dataset
class_0 = pd.DataFrame({
    'feature1':np.random.normal(loc=0,scale=1,size=n_class_0), #feature 1 is a column that takes random but has normal distribution with size class of 0
    'feature2':np.random.normal(loc=0,scale=1,size=n_class_0), #feature 1 is a column that takes random but has normal distribution with size class of 0
    'target':[0]*n_class_0 #target is column with all values 0 and size of class is class 0 size - 900 zeroes will be created

})
class_1 = pd.DataFrame({
    'feature1':np.random.normal(loc=0,scale=1,size=n_class_1),#feature 1 is a column that takes random but has normal distribution with size class of 1
    'feature2':np.random.normal(loc=0,scale=1,size=n_class_1), #feature 1 is a column that takes random but has normal distribution with size class of 1
    'target':[1]*n_class_1 #target is column with all values 1 and size of class is class 1 size - 100 ones will be created
})

In [8]:
df=pd.concat([class_0,class_1]).reset_index(drop=True) #dropping the index that is created

In [9]:
df.head()

   feature1  feature2  target
0 -2.643425 -0.093436       0
1 -0.448991  1.650653       0
2 -0.358907 -0.845004       0
3  0.133194  0.395839       0
4 -0.644242 -1.342092       0

In [10]:
df.tail()

     feature1  feature2  target
995  0.317874 -1.433189       1
996  2.203088 -0.370110       1
997  0.477481 -0.284352       1
998  1.767493  0.373888       1
999 -2.205739  0.263030       1

In [11]:
df['target'].value_counts()

target
0    900
1    100
Name: count, dtype: int64

In [15]:
#upscaling
df_minority=df[df['target']==1]
df_majority=df[df['target']==0]

In [13]:
%pip install scikit-learn

Collecting scikit-learn
  Using cached scikit_learn-1.9.0-cp312-cp312-macosx_12_0_arm64.whl.metadata (11 kB)
Requirement already satisfied: numpy>=1.24.1 in /Users/pravarikakosanam/Desktop/mathematics for ai/venv/lib/python3.12/site-packages (from scikit-learn) (2.5.1)
Collecting scipy>=1.10.0 (from scikit-learn)
  Downloading scipy-1.18.0-cp312-cp312-macosx_14_0_arm64.whl.metadata (62 kB)
Collecting joblib>=1.4.0 (from scikit-learn)
  Using cached joblib-1.5.3-py3-none-any.whl.metadata (5.5 kB)
Collecting narwhals>=2.0.1 (from scikit-learn)
  Downloading narwhals-2.24.0-py3-none-any.whl.metadata (15 kB)
Collecting threadpoolctl>=3.5.0 (from scikit-learn)
  Using cached threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
Using cached scikit_learn-1.9.0-cp312-cp312-macosx_12_0_arm64.whl (8.3 MB)
Using cached joblib-1.5.3-py3-none-any.whl (309 kB)
Downloading narwhals-2.24.0-py3-none-any.whl (461 kB)
Downloading scipy-1.18.0-cp312-cp312-macosx_14_0_arm64.whl (20.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 20.4/20.4 MB 59.0 MB/s eta 0:00:00a 0:00:01
Using cached threadpoolctl-3.6.0-py3-none-any.whl (18 kB)
Installing collected packages: threadpoolctl, scipy, narwhals, joblib, scikit-learn
Successfully installed joblib-1.5.3 narwhals-2.24.0 scikit-learn-1.9.0 scipy-1.18.0 threadpoolctl-3.6.0

[notice] A new release of pip is available: 24.3.1 -> 26.1.2
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [17]:
from sklearn.utils import resample #resample it does create extra points to match majority
df_minority_upscaled=resample(df_minority,replace=True,n_samples=len(df_majority),random_state=42)

In [18]:
df_minority_upscaled.shape

(900, 3)

In [20]:
df_upsampled=pd.concat([df_majority,df_minority_upscaled])

In [21]:
df_upsampled['target'].value_counts()

target
0    900
1    900
Name: count, dtype: int64

In [34]:
#Create my dataframe with imbalance dataset
class_0 = pd.DataFrame({
    'feature1':np.random.normal(loc=0,scale=1,size=n_class_0), #feature 1 is a column that takes random but has normal distribution with size class of 0
    'feature2':np.random.normal(loc=0,scale=1,size=n_class_0), #feature 1 is a column that takes random but has normal distribution with size class of 0
    'target':[0]*n_class_0 #target is column with all values 0 and size of class is class 0 size - 900 zeroes will be created

})
class_1 = pd.DataFrame({
    'feature1':np.random.normal(loc=0,scale=1,size=n_class_1),#feature 1 is a column that takes random but has normal distribution with size class of 1
    'feature2':np.random.normal(loc=0,scale=1,size=n_class_1), #feature 1 is a column that takes random but has normal distribution with size class of 1
    'target':[1]*n_class_1 #target is column with all values 1 and size of class is class 1 size - 100 ones will be created
})

In [35]:
df2=pd.concat([class_0,class_1]).reset_index(drop=True) #dropping the index that is created

In [36]:
df2['target'].value_counts()

target
0    900
1    100
Name: count, dtype: int64

In [37]:
#downscaling
df2_minority=df[df2['target']==1]
df2_majority=df[df2['target']==0]

In [43]:
from sklearn.utils import resample #resample it does create extra points to match majority
df2_downsampled=resample(df2_majority,replace=False,n_samples=len(df2_majority),random_state=42)

In [50]:
df2_downsampled.shape

(1000, 3)

In [51]:
df2_downsampled= pd.concat([df2_minority,df2_majority_downsampled])

In [52]:
df2_downsampled.target.value_counts()

target
0    900
1    100
Name: count, dtype: int64